import { PrismaClient, CollegeType } from '@prisma/client';
import * as argon2 from 'argon2';

const prisma = new PrismaClient();

const collegeData = [
  {
    name: 'Indian Institute of Technology Delhi',
    slug: 'iit-delhi',
    shortName: 'IIT Delhi',
    description: 'One of the premier engineering institutes in India, known for academic excellence and cutting-edge research across engineering, technology, and sciences.',
    overview: 'Established in 1961 as an Institute of National Importance, IIT Delhi is located in Hauz Khas, New Delhi. It has consistently been ranked among the top engineering colleges in India and Asia.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1961,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.8,
    reviewCount: 1250,
    placementAverage: 2500000,
    placementHighest: 12000000,
    popularCourses: ['B.Tech Computer Science', 'B.Tech Electrical', 'M.Tech AI', 'MBA'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Wi-Fi Campus', 'Medical', 'Auditorium'],
    tags: ['Engineering', 'Top Ranked', 'Research', 'IIT'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://home.iitd.ac.in/',
  },
  {
    name: 'Delhi Technological University',
    slug: 'dtu-delhi',
    shortName: 'DTU',
    description: 'A premier technical university in Delhi offering undergraduate, postgraduate, and doctoral programs in engineering and technology.',
    overview: 'Formerly known as Delhi College of Engineering, DTU was established in 1941. It is one of the oldest engineering colleges in India and has produced numerous distinguished alumni.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1941,
    feesMin: 95000,
    feesMax: 190000,
    rating: 4.5,
    reviewCount: 890,
    placementAverage: 1800000,
    placementHighest: 8500000,
    popularCourses: ['B.Tech Computer Science', 'B.Tech Mechanical', 'M.Tech Electronics'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Cafeteria', 'Wi-Fi', 'Innovation Lab'],
    tags: ['Engineering', 'Top Ranked', 'DTU'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.dtu.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    shortName: 'IIT Bombay',
    description: 'One of the most prestigious engineering institutes globally, known for world-class research and innovation.',
    overview: 'Founded in 1958, IIT Bombay is located in Powai, Mumbai. It is consistently ranked among the top engineering institutes in Asia and the world.',
    city: 'Mumbai',
    state: 'Maharashtra',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1958,
    feesMin: 115000,
    feesMax: 230000,
    rating: 4.9,
    reviewCount: 1500,
    placementAverage: 2800000,
    placementHighest: 15000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Aerospace', 'M.Tech Data Science', 'PhD'],
    examsAccepted: ['JEE Advanced', 'GATE'],
    facilities: ['Hostel', 'Library', 'Swimming Pool', 'Sports Complex', 'Research Labs', 'Medical'],
    tags: ['Engineering', 'Top Ranked', 'Research', 'IIT'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitb.ac.in/',
  },
  {
    name: 'National Institute of Technology Raipur',
    slug: 'nit-raipur',
    shortName: 'NIT Raipur',
    description: 'An Institute of National Importance offering quality engineering education in central India.',
    overview: 'Founded in 1956, NIT Raipur (formerly Government Engineering College Raipur) offers various undergraduate and postgraduate programs in engineering and architecture.',
    city: 'Raipur',
    state: 'Chhattisgarh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1956,
    feesMin: 70000,
    feesMax: 140000,
    rating: 4.2,
    reviewCount: 560,
    placementAverage: 800000,
    placementHighest: 4000000,
    popularCourses: ['B.Tech Information Technology', 'B.Tech Mining', 'B.Tech CSE'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Library', 'Cafeteria', 'Sports', 'Wi-Fi'],
    tags: ['Engineering', 'NIT', 'Central India'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitrr.ac.in/',
  },
  {
    name: 'Vellore Institute of Technology',
    slug: 'vit-vellore',
    shortName: 'VIT Vellore',
    description: 'A top-ranked private deemed university offering a wide range of academic programs with excellent placement record.',
    overview: 'VIT was established in 1984 under the leadership of Dr. G. Viswanathan. It is known for its extensive campus, global tie-ups, and exceptional placement record.',
    city: 'Vellore',
    state: 'Tamil Nadu',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1984,
    feesMin: 150000,
    feesMax: 300000,
    rating: 4.5,
    reviewCount: 2100,
    placementAverage: 900000,
    placementHighest: 6000000,
    popularCourses: ['B.Tech CSE', 'BCA', 'MCA', 'B.Tech ECE'],
    examsAccepted: ['VITEEE'],
    facilities: ['AC Hostels', 'Swimming Pool', 'Gym', 'Smart Classrooms', 'Library'],
    tags: ['Engineering', 'Private', 'Placement', 'Deemed'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://vit.ac.in/',
  },
  {
    name: 'Banaras Hindu University',
    slug: 'bhu-varanasi',
    shortName: 'BHU',
    description: 'One of the largest residential universities in Asia, offering diverse programs in arts, science, engineering, and medicine.',
    overview: 'Founded in 1916 by Mahamana Pandit Madan Mohan Malaviya, BHU is located in Varanasi. It is one of the most prestigious central universities in India.',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1916,
    feesMin: 30000,
    feesMax: 100000,
    rating: 4.4,
    reviewCount: 1800,
    placementAverage: 700000,
    placementHighest: 3500000,
    popularCourses: ['B.Tech', 'MBBS', 'BA', 'M.Sc', 'LLB'],
    examsAccepted: ['JEE Main', 'NEET', 'CUET'],
    facilities: ['Hostel', 'Library', 'Hospital', 'Sports', 'Auditorium', 'Wi-Fi'],
    tags: ['Central University', 'Multidisciplinary', 'Research'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.bhu.ac.in/',
  },
  {
    name: 'Pune Institute of Computer Technology',
    slug: 'pict-pune',
    shortName: 'PICT',
    description: 'A leading engineering college in Pune known for its excellent computer science and IT programs.',
    overview: 'PICT was established in 1983 and has been consistently ranked among the top private engineering colleges in Maharashtra.',
    city: 'Pune',
    state: 'Maharashtra',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 1983,
    feesMin: 120000,
    feesMax: 180000,
    rating: 4.3,
    reviewCount: 720,
    placementAverage: 1200000,
    placementHighest: 5500000,
    popularCourses: ['B.Tech CSE', 'B.Tech IT', 'M.Tech CSE'],
    examsAccepted: ['JEE Main', 'MHT-CET'],
    facilities: ['Library', 'Sports', 'Cafeteria', 'Wi-Fi', 'Auditorium'],
    tags: ['Engineering', 'Computer Science', 'Pune'],
    approvedBy: ['AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://pict.edu/',
  },
  {
    name: 'SRM Institute of Science and Technology',
    slug: 'srm-university',
    shortName: 'SRM',
    description: 'A leading private university known for its sprawling campus, diverse programs, and strong industry connections.',
    overview: 'SRM IST was established in 1985 and has grown into one of the largest private universities in India with multiple campuses across Tamil Nadu.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1985,
    feesMin: 180000,
    feesMax: 350000,
    rating: 4.1,
    reviewCount: 1900,
    placementAverage: 750000,
    placementHighest: 4500000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'MBA', 'BBA'],
    examsAccepted: ['SRMJEEE'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Gym', 'Pool', 'Food Court'],
    tags: ['Engineering', 'Private', 'Multi-campus'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.srmist.edu.in/',
  },
  {
    name: 'Amity University Noida',
    slug: 'amity-noida',
    shortName: 'Amity Noida',
    description: 'A leading private university in North India with a focus on innovation, research, and global education.',
    overview: 'Amity University was established in 2005 and is part of the Amity Education Group. It offers programs across engineering, management, law, and humanities.',
    city: 'Noida',
    state: 'Uttar Pradesh',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2005,
    feesMin: 200000,
    feesMax: 500000,
    rating: 4.0,
    reviewCount: 1500,
    placementAverage: 600000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech', 'MBA', 'BBA', 'BA LLB', 'B.Des'],
    examsAccepted: ['Amity JEE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Auditorium', 'Cafeteria', 'Medical'],
    tags: ['Private', 'Multidisciplinary', 'North India'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.amity.edu/',
  },
  {
    name: 'Chandigarh University',
    slug: 'chandigarh-university',
    shortName: 'CU',
    description: 'A leading private university in Punjab known for its excellent placement record and global collaborations.',
    overview: 'Chandigarh University (CU) was established in 2012 and has quickly risen to become one of the top private universities in North India with excellent industry connections.',
    city: 'Mohali',
    state: 'Punjab',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2012,
    feesMin: 160000,
    feesMax: 320000,
    rating: 4.2,
    reviewCount: 1300,
    placementAverage: 850000,
    placementHighest: 4700000,
    popularCourses: ['B.Tech CSE', 'MBA', 'BBA', 'BCA'],
    examsAccepted: ['CUCET'],
    facilities: ['Hostel', 'Library', 'Sports Stadium', 'Gym', 'Wi-Fi', 'Bank'],
    tags: ['Private', 'Placement', 'Chandigarh'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.cuchd.in/',
  },
  {
    name: 'Guru Ghasidas Vishwavidyalaya',
    slug: 'ggu-bilaspur',
    shortName: 'GGU',
    description: 'A central university in Chhattisgarh offering diverse programs in arts, science, engineering, and management.',
    overview: 'Established in 1983, Guru Ghasidas Vishwavidyalaya is a central university located in Bilaspur, Chhattisgarh, offering a wide range of undergraduate and postgraduate programs.',
    city: 'Bilaspur',
    state: 'Chhattisgarh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1983,
    feesMin: 25000,
    feesMax: 70000,
    rating: 3.8,
    reviewCount: 340,
    placementAverage: 400000,
    placementHighest: 1800000,
    popularCourses: ['B.Tech', 'MBA', 'M.Sc', 'BA', 'LLB'],
    examsAccepted: ['CUET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Medical', 'Cafeteria'],
    tags: ['Central University', 'Chhattisgarh'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.ggu.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Kharagpur',
    slug: 'iit-kharagpur',
    shortName: 'IIT KGP',
    description: 'The first IIT established in India, known for its vast campus and pioneering research.',
    overview: 'IIT Kharagpur was established in 1951 as the first IIT. It has the largest campus among all IITs and offers programs in engineering, law, medicine, and management.',
    city: 'Kharagpur',
    state: 'West Bengal',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1951,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.7,
    reviewCount: 1350,
    placementAverage: 2400000,
    placementHighest: 11000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'MBA', 'LLB'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Hospital', 'Sports Stadium', 'Innovation Lab'],
    tags: ['Engineering', 'Top Ranked', 'IIT', 'Research'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitkgp.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Roorkee',
    slug: 'iit-roorkee',
    shortName: 'IIT Roorkee',
    description: 'One of the oldest engineering institutions in Asia, now an IIT with world-class facilities.',
    overview: 'Originally established as Thomason College of Civil Engineering in 1847, IIT Roorkee is the oldest engineering institution in Asia.',
    city: 'Roorkee',
    state: 'Uttarakhand',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1847,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.6,
    reviewCount: 980,
    placementAverage: 2200000,
    placementHighest: 10000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Civil', 'B.Arch', 'M.Tech'],
    examsAccepted: ['JEE Advanced', 'GATE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Medical', 'Wi-Fi', 'Research Labs'],
    tags: ['Engineering', 'Top Ranked', 'IIT', 'Heritage'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitr.ac.in/',
  },
  {
    name: 'Birla Institute of Technology and Science Pilani',
    slug: 'bits-pilani',
    shortName: 'BITS Pilani',
    description: 'A premier deemed university known for its rigorous academic programs and excellent placement record.',
    overview: 'BITS Pilani was established in 1964 and is one of India\'s leading private institutes for engineering and sciences with campuses in Pilani, Goa, and Hyderabad.',
    city: 'Pilani',
    state: 'Rajasthan',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1964,
    feesMin: 250000,
    feesMax: 450000,
    rating: 4.6,
    reviewCount: 1150,
    placementAverage: 2000000,
    placementHighest: 9000000,
    popularCourses: ['B.E. CSE', 'B.E. ECE', 'M.Sc', 'MBA'],
    examsAccepted: ['BITSAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Gym', 'Medical', 'Bank'],
    tags: ['Engineering', 'Top Private', 'Placement'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.bits-pilani.ac.in/',
  },
  {
    name: 'Anna University',
    slug: 'anna-university',
    shortName: 'Anna Univ',
    description: 'A premier technical university in Tamil Nadu, known for its vast network of affiliated colleges.',
    overview: 'Anna University was established in 1978 and is one of the top technical universities in India with a strong focus on engineering and technology education.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1978,
    feesMin: 50000,
    feesMax: 120000,
    rating: 4.3,
    reviewCount: 920,
    placementAverage: 900000,
    placementHighest: 5000000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'M.Tech', 'MCA'],
    examsAccepted: ['TNEA', 'GATE', 'TANCET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Wi-Fi', 'Medical'],
    tags: ['Engineering', 'State University', 'Chennai'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.annauniv.edu/',
  },
  {
    name: 'Manipal Institute of Technology',
    slug: 'manipal-institute',
    shortName: 'MIT Manipal',
    description: 'A leading private engineering institute in Karnataka with a strong focus on innovation and research.',
    overview: 'MIT Manipal was established in 1957 as one of the first private engineering colleges in India. It offers undergraduate and postgraduate programs in engineering and technology.',
    city: 'Manipal',
    state: 'Karnataka',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 1957,
    feesMin: 280000,
    feesMax: 450000,
    rating: 4.4,
    reviewCount: 840,
    placementAverage: 1100000,
    placementHighest: 5500000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical'],
    examsAccepted: ['MET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Hospital', 'Wi-Fi'],
    tags: ['Engineering', 'Private', 'Karnataka'],
    approvedBy: ['AICTE'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://manipal.edu/mit.html',
  },
  {
    name: 'Jamia Millia Islamia',
    slug: 'jamia-millia',
    shortName: 'Jamia',
    description: 'A central university in Delhi offering diverse programs with a strong emphasis on research and inclusivity.',
    overview: 'Jamia Millia Islamia was established in 1920 and became a central university in 1988. It offers programs across engineering, humanities, law, and sciences.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1920,
    feesMin: 25000,
    feesMax: 80000,
    rating: 4.1,
    reviewCount: 670,
    placementAverage: 600000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech', 'BA', 'LLB', 'MBA', 'M.Sc'],
    examsAccepted: ['JEE Main', 'CUET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Medical', 'Auditorium'],
    tags: ['Central University', 'Delhi', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.jmi.ac.in/',
  },
  {
    name: 'University of Delhi',
    slug: 'du-delhi',
    shortName: 'DU',
    description: 'One of the largest and most prestigious universities in India, known for its academic excellence across disciplines.',
    overview: 'Established in 1922, the University of Delhi is a central university located in Delhi with over 90 colleges affiliated to it.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1922,
    feesMin: 15000,
    feesMax: 50000,
    rating: 4.3,
    reviewCount: 2500,
    placementAverage: 500000,
    placementHighest: 2500000,
    popularCourses: ['BA', 'B.Com', 'B.Sc', 'MA', 'MCA'],
    examsAccepted: ['CUET'],
    facilities: ['Library', 'Sports', 'Auditorium', 'Wi-Fi', 'Medical'],
    tags: ['Central University', 'Delhi', 'Arts & Science'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.du.ac.in/',
  },
  {
    name: 'Christ University',
    slug: 'christ-university',
    shortName: 'Christ',
    description: 'A premier private university in Bangalore known for academic excellence and holistic education.',
    overview: 'Christ University was established in 1969 and is one of the top private universities in India, known for its rigorous academic programs and vibrant campus life.',
    city: 'Bangalore',
    state: 'Karnataka',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1969,
    feesMin: 150000,
    feesMax: 300000,
    rating: 4.3,
    reviewCount: 1100,
    placementAverage: 700000,
    placementHighest: 3500000,
    popularCourses: ['BBA', 'BA', 'B.Sc', 'MBA', 'MCA'],
    examsAccepted: ['CUET', 'Christ Entrance'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Cafeteria', 'Wi-Fi'],
    tags: ['Private', 'Bangalore', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://christuniversity.in/',
  },
  {
    name: 'National Institute of Technology Karnataka',
    slug: 'nitk-surathkal',
    shortName: 'NITK Surathkal',
    description: 'A premier NIT located on the coast of Karnataka, known for excellent engineering programs.',
    overview: 'NITK Surathkal was established in 1960 and is one of the top NITs in India. It is located on the picturesque coast near Mangalore.',
    city: 'Mangalore',
    state: 'Karnataka',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1960,
    feesMin: 75000,
    feesMax: 150000,
    rating: 4.4,
    reviewCount: 650,
    placementAverage: 1400000,
    placementHighest: 7000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'M.Tech'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Library', 'Beachside Campus', 'Sports', 'Wi-Fi'],
    tags: ['Engineering', 'NIT', 'Top Ranked'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitk.ac.in/',
  },
  {
    name: 'Indian Institute of Management Ahmedabad',
    slug: 'iim-ahmedabad',
    shortName: 'IIM A',
    description: 'India\'s premier management institute, known for its rigorous MBA program and distinguished alumni.',
    overview: 'IIM Ahmedabad was established in 1961 and is consistently ranked as the top business school in India. It offers MBA, PhD, and executive education programs.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    collegeType: 'AUTONOMOUS' as CollegeType,
    establishedYear: 1961,
    feesMin: 2500000,
    feesMax: 3000000,
    rating: 4.9,
    reviewCount: 450,
    placementAverage: 3500000,
    placementHighest: 10000000,
    popularCourses: ['MBA', 'PGPX', 'PhD'],
    examsAccepted: ['CAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Wi-Fi', 'Medical', 'Auditorium'],
    tags: ['Management', 'Top Ranked', 'IIM'],
    approvedBy: ['MHRD'],
    accreditation: ['AACSB', 'AMBA'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iima.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    slug: 'iit-kanpur',
    shortName: 'IIT Kanpur',
    description: 'One of the premier IITs known for its strong research culture and innovative academic programs.',
    overview: 'IIT Kanpur was established in 1959 with assistance from nine US universities. It is known for its sprawling campus and strong focus on undergraduate research.',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1959,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.7,
    reviewCount: 1080,
    placementAverage: 2300000,
    placementHighest: 11000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Aerospace', 'M.Tech', 'MBA'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Sports Stadium', 'Research Labs', 'Medical'],
    tags: ['Engineering', 'IIT', 'Top Ranked', 'Research'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitk.ac.in/',
  },
  {
    name: 'Jadavpur University',
    slug: 'jadavpur-university',
    shortName: 'JU',
    description: 'A premier state university in West Bengal known for its engineering and arts programs.',
    overview: 'Jadavpur University was established in 1955 and offers programs in engineering, arts, science, and law. It is consistently ranked among the top universities in India.',
    city: 'Kolkata',
    state: 'West Bengal',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1955,
    feesMin: 20000,
    feesMax: 60000,
    rating: 4.2,
    reviewCount: 780,
    placementAverage: 700000,
    placementHighest: 3200000,
    popularCourses: ['B.Tech', 'BA', 'M.Sc', 'MBA'],
    examsAccepted: ['WBJEE', 'CUET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Auditorium', 'Wi-Fi'],
    tags: ['State University', 'Kolkata', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'http://www.jaduniv.edu.in/',
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    slug: 'amrita-university',
    shortName: 'Amrita',
    description: 'A top-ranked private deemed university with multiple campuses across India.',
    overview: 'Amrita Vishwa Vidyapeetham was established in 2003 and has grown into one of the top private universities in India with campuses in Coimbatore, Bengaluru, and Kochi.',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 2003,
    feesMin: 200000,
    feesMax: 400000,
    rating: 4.3,
    reviewCount: 860,
    placementAverage: 950000,
    placementHighest: 5000000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'MBA', 'BBA'],
    examsAccepted: ['Amrita Entrance'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Medical', 'Yoga Center'],
    tags: ['Private', 'Deemed', 'Multi-campus'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A++', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.amrita.edu/',
  },
  {
    name: 'Siksha O Anusandhan University',
    slug: 'soa-university',
    shortName: 'SOA',
    description: 'A top private deemed university in Odisha known for its engineering and medical programs.',
    overview: 'SOA University was established in 2007 and offers programs across engineering, medicine, management, and law with a strong focus on research.',
    city: 'Bhubaneswar',
    state: 'Odisha',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 2007,
    feesMin: 180000,
    feesMax: 350000,
    rating: 3.9,
    reviewCount: 520,
    placementAverage: 550000,
    placementHighest: 2800000,
    popularCourses: ['B.Tech', 'MBBS', 'MBA', 'B.Sc'],
    examsAccepted: ['OJEE', 'NEET'],
    facilities: ['Hostel', 'Library', 'Hospital', 'Sports', 'Wi-Fi'],
    tags: ['Private', 'Deemed', 'Odisha'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.soa.ac.in/',
  },
  {
    name: 'Lovely Professional University',
    slug: 'lpu-punjab',
    shortName: 'LPU',
    description: 'One of the largest private universities in India with a diverse range of academic programs.',
    overview: 'LPU was established in 2005 and has one of the largest campuses in India. It offers over 200 programs across multiple disciplines.',
    city: 'Phagwara',
    state: 'Punjab',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2005,
    feesMin: 160000,
    feesMax: 350000,
    rating: 4.0,
    reviewCount: 1600,
    placementAverage: 650000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech', 'MBA', 'BBA', 'BCA', 'BA LLB'],
    examsAccepted: ['LPUNEST'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Shopping Complex', 'Bank'],
    tags: ['Private', 'Large Campus', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.lpu.in/',
  },
  {
    name: 'Indian Statistical Institute',
    slug: 'isi-kolkata',
    shortName: 'ISI',
    description: 'India\'s premier institute for statistics, mathematics, and data science research and education.',
    overview: 'ISI was founded in 1931 by Professor P.C. Mahalanobis. It is an Institute of National Importance under the Ministry of Statistics and Programme Implementation.',
    city: 'Kolkata',
    state: 'West Bengal',
    collegeType: 'AUTONOMOUS' as CollegeType,
    establishedYear: 1931,
    feesMin: 30000,
    feesMax: 80000,
    rating: 4.7,
    reviewCount: 280,
    placementAverage: 1800000,
    placementHighest: 8000000,
    popularCourses: ['B.Stat', 'M.Stat', 'MS Data Science', 'PhD'],
    examsAccepted: ['ISI Entrance'],
    facilities: ['Hostel', 'Library', 'Research Labs', 'Wi-Fi', 'Auditorium'],
    tags: ['Statistics', 'Data Science', 'Research', 'Top Ranked'],
    approvedBy: ['MHRD'],
    accreditation: [],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.isical.ac.in/',
  },
  {
    name: 'College of Engineering Pune',
    slug: 'coep-pune',
    shortName: 'COEP',
    description: 'One of the oldest engineering colleges in India, known for its academic legacy and strong alumni network.',
    overview: 'COEP was established in 1854 and is one of the oldest engineering colleges in Asia. It offers undergraduate and postgraduate programs in engineering and technology.',
    city: 'Pune',
    state: 'Maharashtra',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1854,
    feesMin: 60000,
    feesMax: 130000,
    rating: 4.3,
    reviewCount: 720,
    placementAverage: 1100000,
    placementHighest: 5500000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'B.Tech Civil', 'M.Tech'],
    examsAccepted: ['JEE Main', 'MHT-CET', 'GATE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Wi-Fi', 'Heritage Campus'],
    tags: ['Engineering', 'Heritage', 'Top Ranked'],
    approvedBy: ['AICTE'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.coep.org.in/',
  },
];

const additionalColleges = [
  {
    name: 'Indian Institute of Technology Madras',
    slug: 'iit-madras',
    shortName: 'IIT Madras',
    description: 'Consistently ranked as the top engineering institute in India by NIRF, offering exceptional research and education opportunities.',
    overview: 'Established in 1959 with technical assistance from the Government of West Germany, IIT Madras is a residential institute situated in a beautiful wood-land campus in Chennai.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1959,
    feesMin: 112000,
    feesMax: 220000,
    rating: 4.9,
    reviewCount: 1450,
    placementAverage: 2600000,
    placementHighest: 13000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Aerospace', 'B.Tech Electrical', 'MBA'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Research Labs', 'Library', 'Sports', 'Wi-Fi', 'Hospital'],
    tags: ['Engineering', 'Top Ranked', 'IIT', 'NIRF Rank 1'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitm.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Guwahati',
    slug: 'iit-guwahati',
    shortName: 'IIT Guwahati',
    description: 'A premier research-intensive institute located on the banks of the Brahmaputra River in Northeast India.',
    overview: 'Established in 1994, IIT Guwahati features a sprawling, scenic campus, and is known for its excellent academic reputation, infrastructure, and world-class research facilities.',
    city: 'Guwahati',
    state: 'Assam',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1994,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.6,
    reviewCount: 880,
    placementAverage: 2100000,
    placementHighest: 9500000,
    popularCourses: ['B.Tech CSE', 'B.Tech Bioscience', 'M.Tech Design', 'M.Sc'],
    examsAccepted: ['JEE Advanced', 'GATE', 'UCEED'],
    facilities: ['Hostel', 'Scenic Campus', 'Library', 'Sports', 'Research Labs', 'Wi-Fi'],
    tags: ['Engineering', 'IIT', 'Northeast', 'Scenic'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitg.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Hyderabad',
    slug: 'iit-hyderabad',
    shortName: 'IITH',
    description: 'A fast-growing premier engineering institute in Telangana known for innovation and collaboration with Japanese universities.',
    overview: 'Founded in 2008, IIT Hyderabad has established itself as a hub of innovation, research and design, particularly in VLSI, AI, and smart mobility.',
    city: 'Sangareddy',
    state: 'Telangana',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 2008,
    feesMin: 115000,
    feesMax: 230000,
    rating: 4.7,
    reviewCount: 540,
    placementAverage: 2000000,
    placementHighest: 8000000,
    popularCourses: ['B.Tech CSE', 'B.Tech AI', 'M.Tech Smart Mobility'],
    examsAccepted: ['JEE Advanced', 'GATE'],
    facilities: ['Hostel', 'Japan Collaboration Lab', 'Library', 'Sports', 'Wi-Fi'],
    tags: ['Engineering', 'IIT', 'New Gen', 'Innovation'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iith.ac.in/',
  },
  {
    name: 'National Institute of Technology Tiruchirappalli',
    slug: 'nit-trichy',
    shortName: 'NIT Trichy',
    description: 'Consistently ranked as the top NIT in India, offering excellent academic programs and industry-aligned training.',
    overview: 'Established in 1964 as Regional Engineering College, NIT Trichy has a sprawling campus near Tiruchirappalli, Tamil Nadu, and features a strong placement track record.',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1964,
    feesMin: 72000,
    feesMax: 145000,
    rating: 4.5,
    reviewCount: 920,
    placementAverage: 1200000,
    placementHighest: 5000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Chemical', 'MBA', 'MCA'],
    examsAccepted: ['JEE Main', 'GATE', 'CAT', 'NIMCET'],
    facilities: ['Hostel', 'Central Library', 'Sports Complex', 'Computing Center', 'Cafeteria'],
    tags: ['Engineering', 'NIT', 'Top Rank', 'Placements'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitt.edu/',
  },
  {
    name: 'National Institute of Technology Calicut',
    slug: 'nit-calicut',
    shortName: 'NIT Calicut',
    description: 'A premier technical institution in Kerala, providing state-of-the-art engineering and science education.',
    overview: 'Established in 1961 as Regional Engineering College Calicut, the institute has evolved into a premier NIT focused on engineering, architecture, and technology.',
    city: 'Kozhikode',
    state: 'Kerala',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1961,
    feesMin: 70000,
    feesMax: 140000,
    rating: 4.3,
    reviewCount: 680,
    placementAverage: 980000,
    placementHighest: 4600000,
    popularCourses: ['B.Tech CSE', 'B.Arch', 'M.Tech'],
    examsAccepted: ['JEE Main', 'NATA', 'GATE'],
    facilities: ['Hostel', 'Digital Library', 'Sports Ground', 'Auditorium', 'Wi-Fi'],
    tags: ['Engineering', 'NIT', 'Kerala', 'Green Campus'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitc.ac.in/',
  },
  {
    name: 'National Institute of Technology Rourkela',
    slug: 'nit-rourkela',
    shortName: 'NIT Rourkela',
    description: 'One of the leading technical institutions in eastern India, known for its extensive research projects and beautiful campus.',
    overview: 'Established in 1961, NIT Rourkela offers multiple programs in engineering, biotechnology, planning, and management. It has one of the largest campuses in India.',
    city: 'Rourkela',
    state: 'Odisha',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1961,
    feesMin: 72000,
    feesMax: 145000,
    rating: 4.4,
    reviewCount: 840,
    placementAverage: 1050000,
    placementHighest: 4800000,
    popularCourses: ['B.Tech CSE', 'B.Tech Metallurgical', 'M.Tech Biotech'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Central Library', 'Sports Stadium', 'Wi-Fi Campus', 'Medical Center'],
    tags: ['Engineering', 'NIT', 'Odisha', 'Research'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitrkl.ac.in/',
  },
  {
    name: 'International Institute of Information Technology Hyderabad',
    slug: 'iiit-hyderabad',
    shortName: 'IIIT Hyderabad',
    description: 'An autonomous research university specializing in information technology, computer science, and electronics.',
    overview: 'Founded in 1998, IIIT Hyderabad is highly regarded for its deep research focus, coding culture (active in ACM-ICPC and GSoC), and unmatched placements.',
    city: 'Hyderabad',
    state: 'Telangana',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 1998,
    feesMin: 300000,
    feesMax: 360000,
    rating: 4.8,
    reviewCount: 620,
    placementAverage: 2800000,
    placementHighest: 10200000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'MS by Research'],
    examsAccepted: ['JEE Main', 'UGEE'],
    facilities: ['Hostel', 'Research Labs', 'Library', 'Sports Complex', 'Wi-Fi'],
    tags: ['Engineering', 'Private', 'Computer Science', 'Top Placements'],
    approvedBy: ['AICTE', 'UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iiit.ac.in/',
  },
  {
    name: 'International Institute of Information Technology Bangalore',
    slug: 'iiit-bangalore',
    shortName: 'IIIT Bangalore',
    description: 'A premier institute in India\'s IT capital, offering highly specialized engineering and IT programs.',
    overview: 'Established in 1999, IIIT Bangalore is an autonomous deemed university located in Electronic City, Bangalore. It is highly valued for its industry linkages and quality education.',
    city: 'Bangalore',
    state: 'Karnataka',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1999,
    feesMin: 320000,
    feesMax: 400000,
    rating: 4.6,
    reviewCount: 410,
    placementAverage: 2400000,
    placementHighest: 7800000,
    popularCourses: ['Integrated M.Tech CSE', 'Integrated M.Tech ECE', 'M.Tech CSE'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Innovation Center', 'Library', 'Sports Complex', 'Cafeteria'],
    tags: ['Engineering', 'Deemed', 'Bangalore', 'Information Technology'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iiitb.ac.in/',
  },
  {
    name: 'Netaji Subhas University of Technology',
    slug: 'nsut-delhi',
    shortName: 'NSUT',
    description: 'A state university in Delhi known for high academic standards and highly successful placements in technology companies.',
    overview: 'Formerly Netaji Subhas Institute of Technology (NSIT), NSUT was established in 1983. It is located in Dwarka, New Delhi and has been a top technical choice for students.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1983,
    feesMin: 150000,
    feesMax: 200000,
    rating: 4.4,
    reviewCount: 820,
    placementAverage: 1600000,
    placementHighest: 7200000,
    popularCourses: ['B.Tech CSE', 'B.Tech IT', 'B.Tech Electronics'],
    examsAccepted: ['JEE Main'],
    facilities: ['Hostel', 'Large Campus', 'Library', 'Sports', 'Auditorium', 'Wi-Fi'],
    tags: ['Engineering', 'Delhi', 'Government', 'High Placements'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nsut.ac.in/',
  },
  {
    name: 'Indira Gandhi Delhi Technical University for Women',
    slug: 'igdtuw-delhi',
    shortName: 'IGDTUW',
    description: 'A premier women\'s university in Delhi, leading in engineering, technology, and science education.',
    overview: 'Established in 2013, IGDTUW is the first engineering university for women in India. It has been highly lauded for empowering women in STEM fields with leading placements.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 2013,
    feesMin: 110000,
    feesMax: 130000,
    rating: 4.5,
    reviewCount: 460,
    placementAverage: 1500000,
    placementHighest: 6000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'B.Arch', 'MCA'],
    examsAccepted: ['JEE Main', 'NIMCET'],
    facilities: ['Safe Hostel', 'Computing Labs', 'Library', 'Gym', 'Wi-Fi', 'Auditorium'],
    tags: ['Engineering', 'Women Empowerment', 'Delhi', 'Placements'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.igdtuw.ac.in/',
  },
  {
    name: 'Punjab Engineering College',
    slug: 'pec-chandigarh',
    shortName: 'PEC',
    description: 'One of the oldest technical institutes in India, offering quality engineering education in Chandigarh.',
    overview: 'Established in 1921, PEC Chandigarh (deemed to be university) is known for its strong heritage, active research projects, and collaborations with aerospace and tech industries.',
    city: 'Chandigarh',
    state: 'Chandigarh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1921,
    feesMin: 90000,
    feesMax: 160000,
    rating: 4.2,
    reviewCount: 540,
    placementAverage: 1100000,
    placementHighest: 4500000,
    popularCourses: ['B.Tech CSE', 'B.Tech Aerospace', 'M.Tech CSE'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Digital Library', 'Sports Grounds', 'Aerospace Lab', 'Wi-Fi'],
    tags: ['Engineering', 'Government', 'Heritage', 'Chandigarh'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://pec.ac.in/',
  },
  {
    name: 'Thapar Institute of Engineering and Technology',
    slug: 'thapar-university',
    shortName: 'TIET Patiala',
    description: 'A leading private deemed engineering university in Punjab, highly valued for its academic rigor.',
    overview: 'Founded in 1956, Thapar University is a private deemed-to-be-university in Patiala, Punjab. It is renowned for its premium infrastructure, academic quality, and high placements.',
    city: 'Patiala',
    state: 'Punjab',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1956,
    feesMin: 220000,
    feesMax: 420000,
    rating: 4.3,
    reviewCount: 1150,
    placementAverage: 950000,
    placementHighest: 4000000,
    popularCourses: ['B.E. Computer Engineering', 'B.E. Electronics', 'MBA'],
    examsAccepted: ['JEE Main', 'TIET Entrance'],
    facilities: ['Hostel', 'State of art Library', 'Sports Center', 'Wi-Fi', 'Cafeterias'],
    tags: ['Engineering', 'Deemed', 'Punjab', 'Top Infrastructure'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.thapar.edu/',
  },
  {
    name: 'Symbiosis International University',
    slug: 'symbiosis-pune',
    shortName: 'SIU Pune',
    description: 'A top-ranked private deemed university offering global standards of education in Pune.',
    overview: 'Established in 1971 by Dr. S. B. Mujumdar, Symbiosis has grown into a highly sought-after private deemed university, famous for management, law, and liberal arts.',
    city: 'Pune',
    state: 'Maharashtra',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1971,
    feesMin: 200000,
    feesMax: 600000,
    rating: 4.4,
    reviewCount: 940,
    placementAverage: 1150000,
    placementHighest: 3800000,
    popularCourses: ['MBA', 'BBA', 'BBA LLB', 'B.Tech'],
    examsAccepted: ['SNAP', 'SET', 'SLAT'],
    facilities: ['AC Hostels', 'Library', 'Amphitheater', 'Sports Arena', 'Gym', 'Wi-Fi'],
    tags: ['Management', 'Law', 'Private', 'Deemed', 'Pune'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A++', 'AMBA'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.siu.edu.in/',
  },
  {
    name: 'Narsee Monjee Institute of Management Studies',
    slug: 'nmims-mumbai',
    shortName: 'NMIMS',
    description: 'A leading private deemed university in Mumbai, highly renowned for its business school.',
    overview: 'NMIMS was established in 1981 and is one of the premier destinations for management education in India. It has expanded to multiple campuses offering tech, law, and commerce.',
    city: 'Mumbai',
    state: 'Maharashtra',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1981,
    feesMin: 250000,
    feesMax: 800000,
    rating: 4.3,
    reviewCount: 1050,
    placementAverage: 1800000,
    placementHighest: 5800000,
    popularCourses: ['MBA', 'BBA', 'B.Tech CSE', 'B.Com'],
    examsAccepted: ['NMAT', 'NPAT'],
    facilities: ['City Campus Hostel', 'Digital Library', 'Finance Lab', 'Auditorium', 'Cafeteria'],
    tags: ['Management', 'Commerce', 'Deemed', 'Mumbai', 'Premium B-School'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A+', 'AACSB'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nmims.edu/',
  },
  {
    name: 'Birla Institute of Technology Mesra',
    slug: 'bit-mesra',
    shortName: 'BIT Mesra',
    description: 'A prominent private deemed technical university in Jharkhand with a long history of excellence.',
    overview: 'Established in 1955 by industrialist B.M. Birla, BIT Mesra has a beautiful green campus in Ranchi and is known for rocket propulsion research and top technical courses.',
    city: 'Ranchi',
    state: 'Jharkhand',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1955,
    feesMin: 140000,
    feesMax: 280000,
    rating: 4.1,
    reviewCount: 620,
    placementAverage: 950000,
    placementHighest: 4400000,
    popularCourses: ['B.Tech CSE', 'B.Tech Space Engineering', 'M.Tech', 'MBA'],
    examsAccepted: ['JEE Main', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Research Labs', 'Wi-Fi'],
    tags: ['Engineering', 'Deemed', 'Eastern India', 'Research'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.bitmesra.ac.in/',
  },
  {
    name: 'PSG College of Technology',
    slug: 'psg-tech',
    shortName: 'PSG Tech',
    description: 'A top-ranked private engineering college in Coimbatore, heavily backed by industry collaborations.',
    overview: 'Established in 1951, PSG Tech is an government-aided private college affiliated to Anna University. It is known for its strong focus on industry-collaborative training.',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 1951,
    feesMin: 60000,
    feesMax: 180000,
    rating: 4.5,
    reviewCount: 780,
    placementAverage: 1000000,
    placementHighest: 4000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Textile', 'M.Tech CSE'],
    examsAccepted: ['TNEA', 'GATE'],
    facilities: ['Hostel', 'Library', 'CNC Workshop', 'Sports Ground', 'Wi-Fi'],
    tags: ['Engineering', 'Private', 'Coimbatore', 'Industry Linked'],
    approvedBy: ['AICTE', 'Anna University'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.psgtech.edu/',
  },
  {
    name: 'Veermata Jijabai Technological Institute',
    slug: 'vjti-mumbai',
    shortName: 'VJTI',
    description: 'One of the oldest technical institutes in Mumbai with high academic repute and placement records.',
    overview: 'VJTI Mumbai was established in 1887. Located in Matunga, Mumbai, it is an autonomous state-funded engineering college with excellent linkages to industries.',
    city: 'Mumbai',
    state: 'Maharashtra',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1887,
    feesMin: 70000,
    feesMax: 90000,
    rating: 4.4,
    reviewCount: 650,
    placementAverage: 1250000,
    placementHighest: 6200000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'MCA', 'Diploma'],
    examsAccepted: ['MHT-CET', 'JEE Main', 'MAH-MCA-CET'],
    facilities: ['Hostel', 'Central Library', 'Sports Grounds', 'Wi-Fi', 'Cafeteria'],
    tags: ['Engineering', 'Government', 'Mumbai', 'Legacy'],
    approvedBy: ['AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.vjti.ac.in/',
  },
  {
    name: 'Sardar Patel Institute of Technology',
    slug: 'spit-mumbai',
    shortName: 'SPIT',
    description: 'A premier private technical college in Mumbai, known for computing and technology programs.',
    overview: 'SPIT was established in 2005 as an autonomous engineering college under Bharatiya Vidya Bhavan. It features state-of-the-art labs and excellent placements in IT.',
    city: 'Mumbai',
    state: 'Maharashtra',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2005,
    feesMin: 140000,
    feesMax: 170000,
    rating: 4.2,
    reviewCount: 380,
    placementAverage: 1050000,
    placementHighest: 4200000,
    popularCourses: ['B.Tech CSE', 'B.Tech AI & Data Science', 'MCA'],
    examsAccepted: ['MHT-CET', 'JEE Main'],
    facilities: ['Library', 'Smart Labs', 'Sports Ground', 'Wi-Fi Campus', 'Cafeteria'],
    tags: ['Engineering', 'Private', 'Mumbai', 'High placements'],
    approvedBy: ['AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.spit.ac.in/',
  },
  {
    name: 'Institute of Chemical Technology',
    slug: 'ict-mumbai',
    shortName: 'ICT Mumbai',
    description: 'A world-renowned technical institute specializing in chemical engineering and technology research.',
    overview: 'Established in 1933, ICT Mumbai (formerly UDCT) is a premier state-funded deemed university. It has produced many successful entrepreneurs and scientists in chemical fields.',
    city: 'Mumbai',
    state: 'Maharashtra',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1933,
    feesMin: 85000,
    feesMax: 120000,
    rating: 4.6,
    reviewCount: 480,
    placementAverage: 900000,
    placementHighest: 3600000,
    popularCourses: ['B.Chem Engg', 'B.Tech Food Tech', 'M.Tech Chemical'],
    examsAccepted: ['MHT-CET', 'JEE Main', 'GATE'],
    facilities: ['Hostel', 'Specialized Labs', 'Rich Library', 'Sports Complex', 'Wi-Fi'],
    tags: ['Chemical', 'Research Focus', 'Government', 'Mumbai'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A++', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.ictmumbai.edu.in/',
  },
  {
    name: 'Aligarh Muslim University',
    slug: 'amu-aligarh',
    shortName: 'AMU',
    description: 'A historic central university offering a huge array of disciplines in Uttar Pradesh.',
    overview: 'Founded by Sir Syed Ahmad Khan in 1875, AMU is a premier central university offering over 300 courses. The campus has traditional heritage architecture and high academic rankings.',
    city: 'Aligarh',
    state: 'Uttar Pradesh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1920,
    feesMin: 20000,
    feesMax: 90000,
    rating: 4.2,
    reviewCount: 1100,
    placementAverage: 650000,
    placementHighest: 2500000,
    popularCourses: ['B.Tech', 'MBBS', 'BA LLB', 'B.Com', 'MA'],
    examsAccepted: ['AMU Entrance', 'NEET', 'CUET'],
    facilities: ['Hostel Network', 'Maulana Azad Library', 'Hospital', 'Sports Complex', 'Museum'],
    tags: ['Central University', 'Heritage', 'Uttar Pradesh'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.amu.ac.in/',
  },
  {
    name: 'Jawaharlal Nehru University',
    slug: 'jnu-delhi',
    shortName: 'JNU',
    description: 'One of the leading universities in India for arts, social sciences, and research.',
    overview: 'Established in 1969, JNU is a world-renowned central university in New Delhi, highly valued for its liberal arts, sciences, international studies, and research programs.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1969,
    feesMin: 500,
    feesMax: 5000,
    rating: 4.5,
    reviewCount: 840,
    placementAverage: 800000,
    placementHighest: 2800000,
    popularCourses: ['MA International Relations', 'BA Foreign Languages', 'M.Sc', 'PhD'],
    examsAccepted: ['CUET PG', 'CUET UG'],
    facilities: ['Hostels', 'Central Library', 'Scenic Green Campus', 'Medical Center', 'Wi-Fi'],
    tags: ['Research', 'Social Sciences', 'Delhi', 'Affordable'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A++'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.jnu.ac.in/',
  },
  {
    name: 'Ashoka University',
    slug: 'ashoka-university',
    shortName: 'Ashoka',
    description: 'A pioneering private liberal arts and sciences university offering world-class multidisciplinary education.',
    overview: 'Established in 2014, Ashoka University is located in Sonepat, Haryana. It focuses on critical thinking, writing, and multidisciplinary programs with ivy-league faculty.',
    city: 'Sonepat',
    state: 'Haryana',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2014,
    feesMin: 700000,
    feesMax: 900000,
    rating: 4.6,
    reviewCount: 320,
    placementAverage: 1100000,
    placementHighest: 3500000,
    popularCourses: ['B.A. Liberal Arts', 'B.Sc Computer Science', 'Young India Fellowship'],
    examsAccepted: ['AAT', 'SAT'],
    facilities: ['Premium AC Hostels', 'Modern Library', 'Sports Center', 'Discussion Rooms', 'Wi-Fi'],
    tags: ['Liberal Arts', 'Private', 'Modern Campus', 'Ivy League Faculty'],
    approvedBy: ['UGC'],
    accreditation: [],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.ashoka.edu.in/',
  },
  {
    name: 'Shiv Nadar University',
    slug: 'snu-noida',
    shortName: 'SNU',
    description: 'A comprehensive, research-focused private university in Greater Noida offering interdisciplinary studies.',
    overview: 'Founded in 2011 by Shiv Nadar (founder of HCL), SNU Noida offers a vibrant residential campus and emphasizes undergraduate research across engineering, sciences, and management.',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2011,
    feesMin: 250000,
    feesMax: 450000,
    rating: 4.2,
    reviewCount: 390,
    placementAverage: 900000,
    placementHighest: 3200000,
    popularCourses: ['B.Tech CSE', 'B.Sc Research', 'MBA'],
    examsAccepted: ['SNUSAT', 'JEE Main', 'CAT'],
    facilities: ['Hostel', 'Large Research Labs', 'Sports Complex', 'Library', 'Wi-Fi'],
    tags: ['Private', 'Research Focus', 'NCR', 'HCL Foundation'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://snu.edu.in/',
  },
  {
    name: 'Nirma University',
    slug: 'nirma-university',
    shortName: 'Nirma',
    description: 'A renowned private university in Ahmedabad, Gujarat, known for engineering, law, and management.',
    overview: 'Established in 2003, Nirma University has become a premier educational brand in western India, offering highly structured academic programs and strong industry placements.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2003,
    feesMin: 180000,
    feesMax: 300000,
    rating: 4.1,
    reviewCount: 570,
    placementAverage: 820000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech CSE', 'MBA', 'B.A. LLB'],
    examsAccepted: ['JEE Main', 'GUJCET', 'CLAT', 'CAT'],
    facilities: ['AC Classrooms', 'Library', 'Sports Facility', 'Cafeterias', 'Wi-Fi'],
    tags: ['Private', 'Gujarat', 'Management & Tech'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://nirmauni.ac.in/',
  },
  {
    name: 'Manipal University Jaipur',
    slug: 'manipal-jaipur',
    shortName: 'MUJ',
    description: 'A modern private university in Rajasthan offering premium infrastructure and high-quality education.',
    overview: 'Established in 2011, MUJ features a state-of-the-art 122-acre residential campus, offering diverse courses in tech, design, management, and media with global linkages.',
    city: 'Jaipur',
    state: 'Rajasthan',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2011,
    feesMin: 190000,
    feesMax: 340000,
    rating: 4.2,
    reviewCount: 710,
    placementAverage: 750000,
    placementHighest: 3200000,
    popularCourses: ['B.Tech CSE', 'B.Des Fashion', 'BBA', 'BJMC'],
    examsAccepted: ['MET', 'JEE Main'],
    facilities: ['Premium Hostels', 'Design Studios', 'Library', 'Sports Arena', 'Wi-Fi'],
    tags: ['Private', 'Jaipur', 'Design & Engineering'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://jaipur.manipal.edu/',
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Seed admin user
  const adminPassword = await argon2.hash('admin123');
  await prisma.user.upsert({
    where: { email: 'admin@campuscompare.com' },
    update: {},
    create: {
      email: 'admin@campuscompare.com',
      name: 'Admin User',
      password: adminPassword,
      role: 'ADMIN',
    },
  });

  // Seed test user
  const userPassword = await argon2.hash('user123');
  await prisma.user.upsert({
    where: { email: 'user@test.com' },
    update: {},
    create: {
      email: 'user@test.com',
      name: 'Test User',
      password: userPassword,
      role: 'USER',
    },
  });

  // Upsert all colleges (create new ones or update existing ones with imageUrl & officialUrl)
  for (const c of [...collegeData, ...additionalColleges]) {
    const courseFee = c.feesMin + Math.floor((c.feesMax - c.feesMin) * 0.7);
    const courseCreateData = c.popularCourses.slice(0, 3).map((courseName, idx) => ({
      name: courseName,
      category: courseName.includes('B.Tech') || courseName.includes('M.Tech') || courseName.includes('B.E.') ? 'Engineering' : 'General',
      degree: courseName.match(/^(B\.\w+|M\.\w+|PhD|PGPX)/)?.[0] || 'Bachelor',
      duration: courseName.startsWith('B.') ? '4 Years' : courseName.startsWith('M.') || courseName === 'MBA' ? '2 Years' : '3 Years',
      fees: idx === 0 ? courseFee : courseFee - Math.floor(courseFee * 0.1 * idx),
    }));

    const existing = await prisma.college.findUnique({ where: { slug: c.slug } });

    if (existing) {
      // Update existing college with imageUrl and officialUrl
      await prisma.college.update({
        where: { slug: c.slug },
        data: {
          imageUrl: c.imageUrl,
          officialUrl: c.officialUrl,
        },
      });
      console.log(`  ✅ Updated: ${c.shortName || c.name} (image + official URL)`);
    } else {
      // Create new college with all data including imageUrl and officialUrl
      await prisma.college.create({
        data: {
          ...c,
          courses: {
            create: courseCreateData,
          },
        },
      });
      console.log(`  🆕 Created: ${c.shortName || c.name}`);
    }
  }

  // Seed reviews for the first 3 colleges
  const collegesForReview = await prisma.college.findMany({ take: 3 });
  const [testUser, adminUser] = await Promise.all([
    prisma.user.findUnique({ where: { email: 'user@test.com' } }),
    prisma.user.findUnique({ where: { email: 'admin@campuscompare.com' } }),
  ]);
  const reviewers = [testUser, adminUser].filter(Boolean) as { id: string }[];

  if (reviewers.length > 0) {
    for (const college of collegesForReview) {
      for (const reviewer of reviewers) {
        const existingReview = await prisma.review.findFirst({
          where: { userId: reviewer.id, collegeId: college.id },
        });
        if (!existingReview) {
          await prisma.review.create({
            data: {
              collegeId: college.id,
              userId: reviewer.id,
              rating: Math.floor(Math.random() * 2) + 3,
              title: college.slug === 'iit-delhi' ? 'World-class education' : 'Great learning experience',
              comment: college.slug === 'iit-delhi'
                ? 'The campus infrastructure is excellent and the faculty is highly knowledgeable. Placement opportunities are outstanding with top companies visiting every year.'
                : 'Good college with decent infrastructure and qualified faculty. The placement cell is active and helps students prepare for interviews.',
              placementRating: Math.floor(Math.random() * 2) + 3,
              facultyRating: Math.floor(Math.random() * 2) + 3,
              campusRating: Math.floor(Math.random() * 2) + 3,
              valueForMoneyRating: Math.floor(Math.random() * 2) + 3,
            },
          });
        }
      }
    }
  }

  // Update college ratings based on actual reviews
  for (const college of collegesForReview) {
    const agg = await prisma.review.aggregate({
      where: { collegeId: college.id },
      _avg: { rating: true },
      _count: true,
    });
    if (agg._count > 0) {
      await prisma.college.update({
        where: { id: college.id },
        data: {
          rating: Number((agg._avg.rating ?? 0).toFixed(1)),
          reviewCount: agg._count,
        },
      });
    }
  }

  console.log(`\n🎓 Seeded ${[...collegeData, ...additionalColleges].length} colleges with images and official URLs.`);
  console.log('✨ Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
