import { PrismaClient, CollegeType } from '@prisma/client';
import * as argon2 from 'argon2';

const prisma = new PrismaClient();

const collegeData = [
  {
    name: 'Indian Institute of Technology Delhi',
    slug: 'iit-delhi',
    shortName: 'IIT Delhi',
    description: 'One of the premier engineering institutes in India, known for academic excellence and cutting-edge research across engineering, technology, and sciences.',
    overview: 'Established in 1961 as an Institute of National Importance, IIT Delhi is located in Hauz Khas, New Delhi. It has consistently been ranked among the top engineering colleges in India and Asia.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1961,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.8,
    reviewCount: 1250,
    placementAverage: 2500000,
    placementHighest: 12000000,
    popularCourses: ['B.Tech Computer Science', 'B.Tech Electrical', 'M.Tech AI', 'MBA'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Wi-Fi Campus', 'Medical', 'Auditorium'],
    tags: ['Engineering', 'Top Ranked', 'Research', 'IIT'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://home.iitd.ac.in/',
  },
  {
    name: 'Delhi Technological University',
    slug: 'dtu-delhi',
    shortName: 'DTU',
    description: 'A premier technical university in Delhi offering undergraduate, postgraduate, and doctoral programs in engineering and technology.',
    overview: 'Formerly known as Delhi College of Engineering, DTU was established in 1941. It is one of the oldest engineering colleges in India and has produced numerous distinguished alumni.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1941,
    feesMin: 95000,
    feesMax: 190000,
    rating: 4.5,
    reviewCount: 890,
    placementAverage: 1800000,
    placementHighest: 8500000,
    popularCourses: ['B.Tech Computer Science', 'B.Tech Mechanical', 'M.Tech Electronics'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Cafeteria', 'Wi-Fi', 'Innovation Lab'],
    tags: ['Engineering', 'Top Ranked', 'DTU'],
    approvedBy: ['UGC', 'AICTE'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.dtu.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    shortName: 'IIT Bombay',
    description: 'One of the most prestigious engineering institutes globally, known for world-class research and innovation.',
    overview: 'Founded in 1958, IIT Bombay is located in Powai, Mumbai. It is consistently ranked among the top engineering institutes in Asia and the world.',
    city: 'Mumbai',
    state: 'Maharashtra',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1958,
    feesMin: 115000,
    feesMax: 230000,
    rating: 4.9,
    reviewCount: 1500,
    placementAverage: 2800000,
    placementHighest: 15000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Aerospace', 'M.Tech Data Science', 'PhD'],
    examsAccepted: ['JEE Advanced', 'GATE'],
    facilities: ['Hostel', 'Library', 'Swimming Pool', 'Sports Complex', 'Research Labs', 'Medical'],
    tags: ['Engineering', 'Top Ranked', 'Research', 'IIT'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitb.ac.in/',
  },
  {
    name: 'National Institute of Technology Raipur',
    slug: 'nit-raipur',
    shortName: 'NIT Raipur',
    description: 'An Institute of National Importance offering quality engineering education in central India.',
    overview: 'Founded in 1956, NIT Raipur (formerly Government Engineering College Raipur) offers various undergraduate and postgraduate programs in engineering and architecture.',
    city: 'Raipur',
    state: 'Chhattisgarh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1956,
    feesMin: 70000,
    feesMax: 140000,
    rating: 4.2,
    reviewCount: 560,
    placementAverage: 800000,
    placementHighest: 4000000,
    popularCourses: ['B.Tech Information Technology', 'B.Tech Mining', 'B.Tech CSE'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Library', 'Cafeteria', 'Sports', 'Wi-Fi'],
    tags: ['Engineering', 'NIT', 'Central India'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitrr.ac.in/',
  },
  {
    name: 'Vellore Institute of Technology',
    slug: 'vit-vellore',
    shortName: 'VIT Vellore',
    description: 'A top-ranked private deemed university offering a wide range of academic programs with excellent placement record.',
    overview: 'VIT was established in 1984 under the leadership of Dr. G. Viswanathan. It is known for its extensive campus, global tie-ups, and exceptional placement record.',
    city: 'Vellore',
    state: 'Tamil Nadu',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1984,
    feesMin: 150000,
    feesMax: 300000,
    rating: 4.5,
    reviewCount: 2100,
    placementAverage: 900000,
    placementHighest: 6000000,
    popularCourses: ['B.Tech CSE', 'BCA', 'MCA', 'B.Tech ECE'],
    examsAccepted: ['VITEEE'],
    facilities: ['AC Hostels', 'Swimming Pool', 'Gym', 'Smart Classrooms', 'Library'],
    tags: ['Engineering', 'Private', 'Placement', 'Deemed'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://vit.ac.in/',
  },
  {
    name: 'Banaras Hindu University',
    slug: 'bhu-varanasi',
    shortName: 'BHU',
    description: 'One of the largest residential universities in Asia, offering diverse programs in arts, science, engineering, and medicine.',
    overview: 'Founded in 1916 by Mahamana Pandit Madan Mohan Malaviya, BHU is located in Varanasi. It is one of the most prestigious central universities in India.',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1916,
    feesMin: 30000,
    feesMax: 100000,
    rating: 4.4,
    reviewCount: 1800,
    placementAverage: 700000,
    placementHighest: 3500000,
    popularCourses: ['B.Tech', 'MBBS', 'BA', 'M.Sc', 'LLB'],
    examsAccepted: ['JEE Main', 'NEET', 'CUET'],
    facilities: ['Hostel', 'Library', 'Hospital', 'Sports', 'Auditorium', 'Wi-Fi'],
    tags: ['Central University', 'Multidisciplinary', 'Research'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.bhu.ac.in/',
  },
  {
    name: 'Pune Institute of Computer Technology',
    slug: 'pict-pune',
    shortName: 'PICT',
    description: 'A leading engineering college in Pune known for its excellent computer science and IT programs.',
    overview: 'PICT was established in 1983 and has been consistently ranked among the top private engineering colleges in Maharashtra.',
    city: 'Pune',
    state: 'Maharashtra',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 1983,
    feesMin: 120000,
    feesMax: 180000,
    rating: 4.3,
    reviewCount: 720,
    placementAverage: 1200000,
    placementHighest: 5500000,
    popularCourses: ['B.Tech CSE', 'B.Tech IT', 'M.Tech CSE'],
    examsAccepted: ['JEE Main', 'MHT-CET'],
    facilities: ['Library', 'Sports', 'Cafeteria', 'Wi-Fi', 'Auditorium'],
    tags: ['Engineering', 'Computer Science', 'Pune'],
    approvedBy: ['AICTE'],
    accreditation: ['NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://pict.edu/',
  },
  {
    name: 'SRM Institute of Science and Technology',
    slug: 'srm-university',
    shortName: 'SRM',
    description: 'A leading private university known for its sprawling campus, diverse programs, and strong industry connections.',
    overview: 'SRM IST was established in 1985 and has grown into one of the largest private universities in India with multiple campuses across Tamil Nadu.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1985,
    feesMin: 180000,
    feesMax: 350000,
    rating: 4.1,
    reviewCount: 1900,
    placementAverage: 750000,
    placementHighest: 4500000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'MBA', 'BBA'],
    examsAccepted: ['SRMJEEE'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Gym', 'Pool', 'Food Court'],
    tags: ['Engineering', 'Private', 'Multi-campus'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.srmist.edu.in/',
  },
  {
    name: 'Amity University Noida',
    slug: 'amity-noida',
    shortName: 'Amity Noida',
    description: 'A leading private university in North India with a focus on innovation, research, and global education.',
    overview: 'Amity University was established in 2005 and is part of the Amity Education Group. It offers programs across engineering, management, law, and humanities.',
    city: 'Noida',
    state: 'Uttar Pradesh',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2005,
    feesMin: 200000,
    feesMax: 500000,
    rating: 4.0,
    reviewCount: 1500,
    placementAverage: 600000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech', 'MBA', 'BBA', 'BA LLB', 'B.Des'],
    examsAccepted: ['Amity JEE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Auditorium', 'Cafeteria', 'Medical'],
    tags: ['Private', 'Multidisciplinary', 'North India'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.amity.edu/',
  },
  {
    name: 'Chandigarh University',
    slug: 'chandigarh-university',
    shortName: 'CU',
    description: 'A leading private university in Punjab known for its excellent placement record and global collaborations.',
    overview: 'Chandigarh University (CU) was established in 2012 and has quickly risen to become one of the top private universities in North India with excellent industry connections.',
    city: 'Mohali',
    state: 'Punjab',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2012,
    feesMin: 160000,
    feesMax: 320000,
    rating: 4.2,
    reviewCount: 1300,
    placementAverage: 850000,
    placementHighest: 4700000,
    popularCourses: ['B.Tech CSE', 'MBA', 'BBA', 'BCA'],
    examsAccepted: ['CUCET'],
    facilities: ['Hostel', 'Library', 'Sports Stadium', 'Gym', 'Wi-Fi', 'Bank'],
    tags: ['Private', 'Placement', 'Chandigarh'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.cuchd.in/',
  },
  {
    name: 'Guru Ghasidas Vishwavidyalaya',
    slug: 'ggu-bilaspur',
    shortName: 'GGU',
    description: 'A central university in Chhattisgarh offering diverse programs in arts, science, engineering, and management.',
    overview: 'Established in 1983, Guru Ghasidas Vishwavidyalaya is a central university located in Bilaspur, Chhattisgarh, offering a wide range of undergraduate and postgraduate programs.',
    city: 'Bilaspur',
    state: 'Chhattisgarh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1983,
    feesMin: 25000,
    feesMax: 70000,
    rating: 3.8,
    reviewCount: 340,
    placementAverage: 400000,
    placementHighest: 1800000,
    popularCourses: ['B.Tech', 'MBA', 'M.Sc', 'BA', 'LLB'],
    examsAccepted: ['CUET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Medical', 'Cafeteria'],
    tags: ['Central University', 'Chhattisgarh'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.ggu.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Kharagpur',
    slug: 'iit-kharagpur',
    shortName: 'IIT KGP',
    description: 'The first IIT established in India, known for its vast campus and pioneering research.',
    overview: 'IIT Kharagpur was established in 1951 as the first IIT. It has the largest campus among all IITs and offers programs in engineering, law, medicine, and management.',
    city: 'Kharagpur',
    state: 'West Bengal',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1951,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.7,
    reviewCount: 1350,
    placementAverage: 2400000,
    placementHighest: 11000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'MBA', 'LLB'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Hospital', 'Sports Stadium', 'Innovation Lab'],
    tags: ['Engineering', 'Top Ranked', 'IIT', 'Research'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitkgp.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Roorkee',
    slug: 'iit-roorkee',
    shortName: 'IIT Roorkee',
    description: 'One of the oldest engineering institutions in Asia, now an IIT with world-class facilities.',
    overview: 'Originally established as Thomason College of Civil Engineering in 1847, IIT Roorkee is the oldest engineering institution in Asia.',
    city: 'Roorkee',
    state: 'Uttarakhand',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1847,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.6,
    reviewCount: 980,
    placementAverage: 2200000,
    placementHighest: 10000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Civil', 'B.Arch', 'M.Tech'],
    examsAccepted: ['JEE Advanced', 'GATE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Medical', 'Wi-Fi', 'Research Labs'],
    tags: ['Engineering', 'Top Ranked', 'IIT', 'Heritage'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitr.ac.in/',
  },
  {
    name: 'Birla Institute of Technology and Science Pilani',
    slug: 'bits-pilani',
    shortName: 'BITS Pilani',
    description: 'A premier deemed university known for its rigorous academic programs and excellent placement record.',
    overview: 'BITS Pilani was established in 1964 and is one of India\'s leading private institutes for engineering and sciences with campuses in Pilani, Goa, and Hyderabad.',
    city: 'Pilani',
    state: 'Rajasthan',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1964,
    feesMin: 250000,
    feesMax: 450000,
    rating: 4.6,
    reviewCount: 1150,
    placementAverage: 2000000,
    placementHighest: 9000000,
    popularCourses: ['B.E. CSE', 'B.E. ECE', 'M.Sc', 'MBA'],
    examsAccepted: ['BITSAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Gym', 'Medical', 'Bank'],
    tags: ['Engineering', 'Top Private', 'Placement'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.bits-pilani.ac.in/',
  },
  {
    name: 'Anna University',
    slug: 'anna-university',
    shortName: 'Anna Univ',
    description: 'A premier technical university in Tamil Nadu, known for its vast network of affiliated colleges.',
    overview: 'Anna University was established in 1978 and is one of the top technical universities in India with a strong focus on engineering and technology education.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1978,
    feesMin: 50000,
    feesMax: 120000,
    rating: 4.3,
    reviewCount: 920,
    placementAverage: 900000,
    placementHighest: 5000000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'M.Tech', 'MCA'],
    examsAccepted: ['TNEA', 'GATE', 'TANCET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Wi-Fi', 'Medical'],
    tags: ['Engineering', 'State University', 'Chennai'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.annauniv.edu/',
  },
  {
    name: 'Manipal Institute of Technology',
    slug: 'manipal-institute',
    shortName: 'MIT Manipal',
    description: 'A leading private engineering institute in Karnataka with a strong focus on innovation and research.',
    overview: 'MIT Manipal was established in 1957 as one of the first private engineering colleges in India. It offers undergraduate and postgraduate programs in engineering and technology.',
    city: 'Manipal',
    state: 'Karnataka',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 1957,
    feesMin: 280000,
    feesMax: 450000,
    rating: 4.4,
    reviewCount: 840,
    placementAverage: 1100000,
    placementHighest: 5500000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical'],
    examsAccepted: ['MET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Hospital', 'Wi-Fi'],
    tags: ['Engineering', 'Private', 'Karnataka'],
    approvedBy: ['AICTE'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://manipal.edu/mit.html',
  },
  {
    name: 'Jamia Millia Islamia',
    slug: 'jamia-millia',
    shortName: 'Jamia',
    description: 'A central university in Delhi offering diverse programs with a strong emphasis on research and inclusivity.',
    overview: 'Jamia Millia Islamia was established in 1920 and became a central university in 1988. It offers programs across engineering, humanities, law, and sciences.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1920,
    feesMin: 25000,
    feesMax: 80000,
    rating: 4.1,
    reviewCount: 670,
    placementAverage: 600000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech', 'BA', 'LLB', 'MBA', 'M.Sc'],
    examsAccepted: ['JEE Main', 'CUET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Medical', 'Auditorium'],
    tags: ['Central University', 'Delhi', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.jmi.ac.in/',
  },
  {
    name: 'University of Delhi',
    slug: 'du-delhi',
    shortName: 'DU',
    description: 'One of the largest and most prestigious universities in India, known for its academic excellence across disciplines.',
    overview: 'Established in 1922, the University of Delhi is a central university located in Delhi with over 90 colleges affiliated to it.',
    city: 'New Delhi',
    state: 'Delhi',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1922,
    feesMin: 15000,
    feesMax: 50000,
    rating: 4.3,
    reviewCount: 2500,
    placementAverage: 500000,
    placementHighest: 2500000,
    popularCourses: ['BA', 'B.Com', 'B.Sc', 'MA', 'MCA'],
    examsAccepted: ['CUET'],
    facilities: ['Library', 'Sports', 'Auditorium', 'Wi-Fi', 'Medical'],
    tags: ['Central University', 'Delhi', 'Arts & Science'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.du.ac.in/',
  },
  {
    name: 'Christ University',
    slug: 'christ-university',
    shortName: 'Christ',
    description: 'A premier private university in Bangalore known for academic excellence and holistic education.',
    overview: 'Christ University was established in 1969 and is one of the top private universities in India, known for its rigorous academic programs and vibrant campus life.',
    city: 'Bangalore',
    state: 'Karnataka',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 1969,
    feesMin: 150000,
    feesMax: 300000,
    rating: 4.3,
    reviewCount: 1100,
    placementAverage: 700000,
    placementHighest: 3500000,
    popularCourses: ['BBA', 'BA', 'B.Sc', 'MBA', 'MCA'],
    examsAccepted: ['CUET', 'Christ Entrance'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Cafeteria', 'Wi-Fi'],
    tags: ['Private', 'Bangalore', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://christuniversity.in/',
  },
  {
    name: 'National Institute of Technology Karnataka',
    slug: 'nitk-surathkal',
    shortName: 'NITK Surathkal',
    description: 'A premier NIT located on the coast of Karnataka, known for excellent engineering programs.',
    overview: 'NITK Surathkal was established in 1960 and is one of the top NITs in India. It is located on the picturesque coast near Mangalore.',
    city: 'Mangalore',
    state: 'Karnataka',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1960,
    feesMin: 75000,
    feesMax: 150000,
    rating: 4.4,
    reviewCount: 650,
    placementAverage: 1400000,
    placementHighest: 7000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'M.Tech'],
    examsAccepted: ['JEE Main', 'GATE'],
    facilities: ['Hostel', 'Library', 'Beachside Campus', 'Sports', 'Wi-Fi'],
    tags: ['Engineering', 'NIT', 'Top Ranked'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.nitk.ac.in/',
  },
  {
    name: 'Indian Institute of Management Ahmedabad',
    slug: 'iim-ahmedabad',
    shortName: 'IIM A',
    description: 'India\'s premier management institute, known for its rigorous MBA program and distinguished alumni.',
    overview: 'IIM Ahmedabad was established in 1961 and is consistently ranked as the top business school in India. It offers MBA, PhD, and executive education programs.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    collegeType: 'AUTONOMOUS' as CollegeType,
    establishedYear: 1961,
    feesMin: 2500000,
    feesMax: 3000000,
    rating: 4.9,
    reviewCount: 450,
    placementAverage: 3500000,
    placementHighest: 10000000,
    popularCourses: ['MBA', 'PGPX', 'PhD'],
    examsAccepted: ['CAT'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Wi-Fi', 'Medical', 'Auditorium'],
    tags: ['Management', 'Top Ranked', 'IIM'],
    approvedBy: ['MHRD'],
    accreditation: ['AACSB', 'AMBA'],
    imageUrl: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iima.ac.in/',
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    slug: 'iit-kanpur',
    shortName: 'IIT Kanpur',
    description: 'One of the premier IITs known for its strong research culture and innovative academic programs.',
    overview: 'IIT Kanpur was established in 1959 with assistance from nine US universities. It is known for its sprawling campus and strong focus on undergraduate research.',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1959,
    feesMin: 110000,
    feesMax: 220000,
    rating: 4.7,
    reviewCount: 1080,
    placementAverage: 2300000,
    placementHighest: 11000000,
    popularCourses: ['B.Tech CSE', 'B.Tech Aerospace', 'M.Tech', 'MBA'],
    examsAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    facilities: ['Hostel', 'Library', 'Sports Stadium', 'Research Labs', 'Medical'],
    tags: ['Engineering', 'IIT', 'Top Ranked', 'Research'],
    approvedBy: ['UGC', 'MHRD'],
    accreditation: ['NAAC A+'],
    imageUrl: 'https://images.unsplash.com/photo-1592289140166-07d2ab28b0ce?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.iitk.ac.in/',
  },
  {
    name: 'Jadavpur University',
    slug: 'jadavpur-university',
    shortName: 'JU',
    description: 'A premier state university in West Bengal known for its engineering and arts programs.',
    overview: 'Jadavpur University was established in 1955 and offers programs in engineering, arts, science, and law. It is consistently ranked among the top universities in India.',
    city: 'Kolkata',
    state: 'West Bengal',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1955,
    feesMin: 20000,
    feesMax: 60000,
    rating: 4.2,
    reviewCount: 780,
    placementAverage: 700000,
    placementHighest: 3200000,
    popularCourses: ['B.Tech', 'BA', 'M.Sc', 'MBA'],
    examsAccepted: ['WBJEE', 'CUET'],
    facilities: ['Hostel', 'Library', 'Sports', 'Auditorium', 'Wi-Fi'],
    tags: ['State University', 'Kolkata', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A'],
    imageUrl: 'https://images.unsplash.com/photo-1525926472898-1c4b78f89e5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'http://www.jaduniv.edu.in/',
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    slug: 'amrita-university',
    shortName: 'Amrita',
    description: 'A top-ranked private deemed university with multiple campuses across India.',
    overview: 'Amrita Vishwa Vidyapeetham was established in 2003 and has grown into one of the top private universities in India with campuses in Coimbatore, Bengaluru, and Kochi.',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 2003,
    feesMin: 200000,
    feesMax: 400000,
    rating: 4.3,
    reviewCount: 860,
    placementAverage: 950000,
    placementHighest: 5000000,
    popularCourses: ['B.Tech CSE', 'B.Tech ECE', 'MBA', 'BBA'],
    examsAccepted: ['Amrita Entrance'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Medical', 'Yoga Center'],
    tags: ['Private', 'Deemed', 'Multi-campus'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A++', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.amrita.edu/',
  },
  {
    name: 'Siksha O Anusandhan University',
    slug: 'soa-university',
    shortName: 'SOA',
    description: 'A top private deemed university in Odisha known for its engineering and medical programs.',
    overview: 'SOA University was established in 2007 and offers programs across engineering, medicine, management, and law with a strong focus on research.',
    city: 'Bhubaneswar',
    state: 'Odisha',
    collegeType: 'DEEMED' as CollegeType,
    establishedYear: 2007,
    feesMin: 180000,
    feesMax: 350000,
    rating: 3.9,
    reviewCount: 520,
    placementAverage: 550000,
    placementHighest: 2800000,
    popularCourses: ['B.Tech', 'MBBS', 'MBA', 'B.Sc'],
    examsAccepted: ['OJEE', 'NEET'],
    facilities: ['Hostel', 'Library', 'Hospital', 'Sports', 'Wi-Fi'],
    tags: ['Private', 'Deemed', 'Odisha'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.soa.ac.in/',
  },
  {
    name: 'Lovely Professional University',
    slug: 'lpu-punjab',
    shortName: 'LPU',
    description: 'One of the largest private universities in India with a diverse range of academic programs.',
    overview: 'LPU was established in 2005 and has one of the largest campuses in India. It offers over 200 programs across multiple disciplines.',
    city: 'Phagwara',
    state: 'Punjab',
    collegeType: 'PRIVATE' as CollegeType,
    establishedYear: 2005,
    feesMin: 160000,
    feesMax: 350000,
    rating: 4.0,
    reviewCount: 1600,
    placementAverage: 650000,
    placementHighest: 3000000,
    popularCourses: ['B.Tech', 'MBA', 'BBA', 'BCA', 'BA LLB'],
    examsAccepted: ['LPUNEST'],
    facilities: ['Hostel', 'Library', 'Sports', 'Gym', 'Shopping Complex', 'Bank'],
    tags: ['Private', 'Large Campus', 'Multidisciplinary'],
    approvedBy: ['UGC'],
    accreditation: ['NAAC A+', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.lpu.in/',
  },
  {
    name: 'Indian Statistical Institute',
    slug: 'isi-kolkata',
    shortName: 'ISI',
    description: 'India\'s premier institute for statistics, mathematics, and data science research and education.',
    overview: 'ISI was founded in 1931 by Professor P.C. Mahalanobis. It is an Institute of National Importance under the Ministry of Statistics and Programme Implementation.',
    city: 'Kolkata',
    state: 'West Bengal',
    collegeType: 'AUTONOMOUS' as CollegeType,
    establishedYear: 1931,
    feesMin: 30000,
    feesMax: 80000,
    rating: 4.7,
    reviewCount: 280,
    placementAverage: 1800000,
    placementHighest: 8000000,
    popularCourses: ['B.Stat', 'M.Stat', 'MS Data Science', 'PhD'],
    examsAccepted: ['ISI Entrance'],
    facilities: ['Hostel', 'Library', 'Research Labs', 'Wi-Fi', 'Auditorium'],
    tags: ['Statistics', 'Data Science', 'Research', 'Top Ranked'],
    approvedBy: ['MHRD'],
    accreditation: [],
    imageUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.isical.ac.in/',
  },
  {
    name: 'College of Engineering Pune',
    slug: 'coep-pune',
    shortName: 'COEP',
    description: 'One of the oldest engineering colleges in India, known for its academic legacy and strong alumni network.',
    overview: 'COEP was established in 1854 and is one of the oldest engineering colleges in Asia. It offers undergraduate and postgraduate programs in engineering and technology.',
    city: 'Pune',
    state: 'Maharashtra',
    collegeType: 'GOVERNMENT' as CollegeType,
    establishedYear: 1854,
    feesMin: 60000,
    feesMax: 130000,
    rating: 4.3,
    reviewCount: 720,
    placementAverage: 1100000,
    placementHighest: 5500000,
    popularCourses: ['B.Tech CSE', 'B.Tech Mechanical', 'B.Tech Civil', 'M.Tech'],
    examsAccepted: ['JEE Main', 'MHT-CET', 'GATE'],
    facilities: ['Hostel', 'Library', 'Sports', 'Wi-Fi', 'Heritage Campus'],
    tags: ['Engineering', 'Heritage', 'Top Ranked'],
    approvedBy: ['AICTE'],
    accreditation: ['NAAC A', 'NBA'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80',
    officialUrl: 'https://www.coep.org.in/',
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Seed admin user
  const adminPassword = await argon2.hash('admin123');
  await prisma.user.upsert({
    where: { email: 'admin@campuscompare.com' },
    update: {},
    create: {
      email: 'admin@campuscompare.com',
      name: 'Admin User',
      password: adminPassword,
      role: 'ADMIN',
    },
  });

  // Seed test user
  const userPassword = await argon2.hash('user123');
  await prisma.user.upsert({
    where: { email: 'user@test.com' },
    update: {},
    create: {
      email: 'user@test.com',
      name: 'Test User',
      password: userPassword,
      role: 'USER',
    },
  });

  // Upsert all colleges (create new ones or update existing ones with imageUrl & officialUrl)
  for (const c of collegeData) {
    const courseFee = c.feesMin + Math.floor((c.feesMax - c.feesMin) * 0.7);
    const courseCreateData = c.popularCourses.slice(0, 3).map((courseName, idx) => ({
      name: courseName,
      category: courseName.includes('B.Tech') || courseName.includes('M.Tech') || courseName.includes('B.E.') ? 'Engineering' : 'General',
      degree: courseName.match(/^(B\.\w+|M\.\w+|PhD|PGPX)/)?.[0] || 'Bachelor',
      duration: courseName.startsWith('B.') ? '4 Years' : courseName.startsWith('M.') || courseName === 'MBA' ? '2 Years' : '3 Years',
      fees: idx === 0 ? courseFee : courseFee - Math.floor(courseFee * 0.1 * idx),
    }));

    const existing = await prisma.college.findUnique({ where: { slug: c.slug } });

    if (existing) {
      // Update existing college with imageUrl and officialUrl
      await prisma.college.update({
        where: { slug: c.slug },
        data: {
          imageUrl: c.imageUrl,
          officialUrl: c.officialUrl,
        },
      });
      console.log(`  ✅ Updated: ${c.shortName || c.name} (image + official URL)`);
    } else {
      // Create new college with all data including imageUrl and officialUrl
      await prisma.college.create({
        data: {
          ...c,
          courses: {
            create: courseCreateData,
          },
        },
      });
      console.log(`  🆕 Created: ${c.shortName || c.name}`);
    }
  }

  // Seed reviews for the first 3 colleges
  const collegesForReview = await prisma.college.findMany({ take: 3 });
  const [testUser, adminUser] = await Promise.all([
    prisma.user.findUnique({ where: { email: 'user@test.com' } }),
    prisma.user.findUnique({ where: { email: 'admin@campuscompare.com' } }),
  ]);
  const reviewers = [testUser, adminUser].filter(Boolean) as { id: string }[];

  if (reviewers.length > 0) {
    for (const college of collegesForReview) {
      for (const reviewer of reviewers) {
        const existingReview = await prisma.review.findFirst({
          where: { userId: reviewer.id, collegeId: college.id },
        });
        if (!existingReview) {
          await prisma.review.create({
            data: {
              collegeId: college.id,
              userId: reviewer.id,
              rating: Math.floor(Math.random() * 2) + 3,
              title: college.slug === 'iit-delhi' ? 'World-class education' : 'Great learning experience',
              comment: college.slug === 'iit-delhi'
                ? 'The campus infrastructure is excellent and the faculty is highly knowledgeable. Placement opportunities are outstanding with top companies visiting every year.'
                : 'Good college with decent infrastructure and qualified faculty. The placement cell is active and helps students prepare for interviews.',
              placementRating: Math.floor(Math.random() * 2) + 3,
              facultyRating: Math.floor(Math.random() * 2) + 3,
              campusRating: Math.floor(Math.random() * 2) + 3,
              valueForMoneyRating: Math.floor(Math.random() * 2) + 3,
            },
          });
        }
      }
    }
  }

  // Update college ratings based on actual reviews
  for (const college of collegesForReview) {
    const agg = await prisma.review.aggregate({
      where: { collegeId: college.id },
      _avg: { rating: true },
      _count: true,
    });
    if (agg._count > 0) {
      await prisma.college.update({
        where: { id: college.id },
        data: {
          rating: Number((agg._avg.rating ?? 0).toFixed(1)),
          reviewCount: agg._count,
        },
      });
    }
  }

  console.log(`\n🎓 Seeded ${collegeData.length} colleges with images and official URLs.`);
  console.log('✨ Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
